preset_base: ${PRESET_BASE}
chain_id: ${CHAIN_ID}
deposit_contract_address: "${DEPOSIT_CONTRACT_ADDRESS}"
mnemonic: ${EL_AND_CL_MNEMONIC}
el_premine:
  "m/44'/60'/0'/0/0": 1000000000ETH
  "m/44'/60'/0'/0/1": 1000000000ETH
  "m/44'/60'/0'/0/2": 1000000000ETH
  "m/44'/60'/0'/0/3": 1000000000ETH
  "m/44'/60'/0'/0/4": 1000000000ETH
  "m/44'/60'/0'/0/5": 1000000000ETH
  "m/44'/60'/0'/0/6": 1000000000ETH
  "m/44'/60'/0'/0/7": 1000000000ETH
  "m/44'/60'/0'/0/8": 1000000000ETH
  "m/44'/60'/0'/0/9": 1000000000ETH
  "m/44'/60'/0'/0/10": 1000000000ETH
  "m/44'/60'/0'/0/11": 1000000000ETH
  "m/44'/60'/0'/0/12": 1000000000ETH
  "m/44'/60'/0'/0/13": 1000000000ETH
  "m/44'/60'/0'/0/14": 1000000000ETH
  "m/44'/60'/0'/0/15": 1000000000ETH
  "m/44'/60'/0'/0/16": 1000000000ETH
  "m/44'/60'/0'/0/17": 1000000000ETH
  "m/44'/60'/0'/0/18": 1000000000ETH
  "m/44'/60'/0'/0/19": 1000000000ETH
  "m/44'/60'/0'/0/20": 1000000000ETH
el_premine_addrs: ${EL_PREMINE_ADDRS}
additional_preloaded_contracts: ${ADDITIONAL_PRELOADED_CONTRACTS}
genesis_timestamp: ${GENESIS_TIMESTAMP}
genesis_delay: ${GENESIS_DELAY}
genesis_gaslimit: ${GENESIS_GASLIMIT}
slot_duration_in_seconds: ${SLOT_DURATION_IN_SECONDS}
electra_fork_epoch: ${ELECTRA_FORK_EPOCH}
